application:
  name: ratings
  namespace: ratings
  local: false 

db:
  # container: "postgres:latest"
  container: "wzy1935/ratings_db:v2"
  containerPort: 5432

dbService:
  port: 5432
  targetPort: 5432

be:
  container: "kokonot88/ratings_be:v2"
  containerPort: 8080

beService:
  port: 8080
  targetPort: 8080

fe:
  container: "wzy1935/ratings_fe:v3"
  containerPort: 80

feService:
  port: 80
  targetPort: 80