kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ratings
  name: ratings-viewer
rules:
- apiGroups: ["*"] 
  resources: ["pods","deployments","services","configmaps","jobs"] 
  verbs: ["get", "list", "watch"] 

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ratings
  name: ratings-developer
rules:
- apiGroups: ["*"] 
  resources: ["*"]
  verbs: ["get", "list", "watch","create","patch","delete","update"] 
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ratings-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]