apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-be-service
  namespace: {{ .Values.application.namespace }}
spec:
  selector:
    app: {{ .Values.application.name }}-be
  ports:
  - protocol: TCP
    port: {{ .Values.beService.port }}
    targetPort: {{ .Values.beService.targetPort }}